// ═══════════════════════════════════════
//  BOSS ENCOUNTERS
//  Each entry: { name, npcId } | { name, npcId, rare: true } | { section } | { name, npcId: null } for events
// ═══════════════════════════════════════
const BOSS_ENCOUNTERS = {
  rfc: [
    { name: 'Oggleflint', npcId: 11517 },
    { name: 'Taragaman the Hungerer', npcId: 11520 },
    { name: 'Jergosh the Invoker', npcId: 11518 },
    { name: 'Bazzalan', npcId: 11519 },
  ],
  wc: [
    { name: 'Kresh', npcId: 3653 },
    { name: 'Skum', npcId: 3674 },
    { name: 'Deviate Faerie Dragon', npcId: 5912, rare: true },
    { name: 'Lady Anacondra', npcId: 3671 },
    { name: 'Lord Cobrahn', npcId: 3669 },
    { name: 'Lord Pythas', npcId: 3670 },
    { name: 'Lord Serpentis', npcId: 3673 },
    { name: 'Verdan the Everliving', npcId: 5775 },
    { name: 'Mutanus the Devourer', npcId: 3654 },
  ],
  deadmines: [
    { name: "Rhahk'Zor", npcId: 644 },
    { name: 'Miner Johnson', npcId: 3586, rare: true },
    { name: "Sneed's Shredder", npcId: 643 },
    { name: 'Gilnid', npcId: 1763 },
    { name: 'Mr. Smite', npcId: 646 },
    { name: 'Captain Greenskin', npcId: 647 },
    { name: 'Cookie', npcId: 645 },
    { name: 'Edwin VanCleef', npcId: 639 },
  ],
  sfk: [
    { name: 'Rethilgore', npcId: 3914 },
    { name: 'The Stable', event: true, bosses: [
      { name: 'Fel Steed', npcId: 3864 },
      { name: 'Shadow Charger', npcId: 3865 },
    ]},
    { name: 'Razorclaw the Butcher', npcId: 3886 },
    { name: 'Baron Silverlaine', npcId: 3887 },
    { name: 'Commander Springvale', npcId: 4278 },
    { name: 'Odo the Blindwatcher', npcId: 4279 },
    { name: 'Deathsworn Captain', npcId: 3872, rare: true },
    { name: 'Fenrus the Devourer', npcId: 4274 },
    { name: 'Wolf Master Nandos', npcId: 3927 },
    { name: 'Archmage Arugal', npcId: 4275 },
  ],
  stockades: [
    { name: 'Targorr the Dread', npcId: 1696 },
    { name: 'Kam Deepfury', npcId: 1666 },
    { name: 'Hamhock', npcId: 1717 },
    { name: 'Bazil Thredd', npcId: 1716 },
    { name: 'Dextren Ward', npcId: 1663 },
    { name: 'Bruegal Ironknuckle', npcId: 1720, rare: true },
  ],
  bfd: [
    { name: 'Ghamoo-Ra', npcId: 4887 },
    { name: 'Lady Sarevess', npcId: 4831 },
    { name: 'Gelihast', npcId: 6243 },
    { name: 'Lorgus Jett', npcId: 12902 },
    { name: 'Twilight Lord Kelris', npcId: 4832 },
    { name: "Old Serra'kis", npcId: 4830 },
    { name: "Aku'mai", npcId: 4829 },
    { section: 'Horde Only' },
    { name: 'Baron Aquanis', npcId: 12876 },
  ],
  gnomer: [
    { name: 'Grubbis', npcId: 7361 },
    { name: 'Viscous Fallout', npcId: 7079 },
    { name: 'Electrocutioner 6000', npcId: 6235 },
    { name: 'Crowd Pummeler 9-60', npcId: 6229 },
    { name: 'Dark Iron Ambassador', npcId: 6228, rare: true },
    { name: 'Mekgineer Thermaplugg', npcId: 7800 },
  ],
  rfk: [
    { name: 'Roogug', npcId: 6168 },
    { name: 'Aggem Thorncurse', npcId: 4424 },
    { name: 'Death Speaker Jargba', npcId: 4428 },
    { name: 'Overlord Ramtusk', npcId: 4420 },
    { name: 'Agathelos the Raging', npcId: 4422 },
    { name: 'Earthcaller Halmgar', npcId: 4842, rare: true },
    { name: 'Blind Hunter', npcId: 4425, rare: true },
    { name: 'Charlga Razorflank', npcId: 4421 },
  ],
  sm: [
    { section: 'Graveyard' },
    { name: 'Interrogator Vishas', npcId: 3983 },
    { name: 'Bloodmage Thalnos', npcId: 4543 },
    { name: 'Azshir the Sleepless', npcId: 6490, rare: true },
    { name: 'Fallen Champion', npcId: 6488, rare: true },
    { name: 'Ironspine', npcId: 6489, rare: true },
    { section: 'Library' },
    { name: 'Houndmaster Loksey', npcId: 3974 },
    { name: 'Arcanist Doan', npcId: 6487 },
    { section: 'Armory' },
    { name: 'Herod', npcId: 3975 },
    { section: 'Cathedral' },
    { name: 'Scarlet Commander Mograine', npcId: 3976 },
    { name: 'High Inquisitor Whitemane', npcId: 3977 },
    { name: 'High Inquisitor Fairbanks', npcId: 4542 },
  ],
  rfd: [
    { name: "Tuten'kash", npcId: 7355 },
    { name: 'Ragglesnout', npcId: 7354, rare: true },
    { name: 'Mordresh Fire Eye', npcId: 7357 },
    { name: 'Glutton', npcId: 8567 },
    { name: 'Plaguemaw the Rotting', npcId: 7356 },
    { name: 'Amnennar the Coldbringer', npcId: 7358 },
  ],
  uldaman: [
    { name: 'Revelosh', npcId: 6910 },
    { name: 'Ironaya', npcId: 7228 },
    { name: 'Obsidian Sentinel', npcId: 7023 },
    { name: 'Ancient Stone Keeper', npcId: 7206 },
    { name: 'Galgann Firehammer', npcId: 7291 },
    { name: 'Grimlok', npcId: 4854 },
    { name: 'Archaedas', npcId: 2748 },
    { section: 'Horde Only' },
    { name: 'Baelog', npcId: 6906 },
    { name: 'Eric the Swift', npcId: 6907 },
    { name: 'Olaf', npcId: 6908 },
  ],
  zf: [
    { name: "Antu'sul", npcId: 8127 },
    { name: 'Theka the Martyr', npcId: 7272 },
    { name: 'Sandarr Dunereaver', npcId: 10080, rare: true },
    { name: 'Sandfury Executioner', npcId: 7274 },
    { name: 'Zerillis', npcId: 10082, rare: true },
    { name: 'Dustwraith', npcId: 10081, rare: true },
    { name: "Witch Doctor Zum'rah", npcId: 7271 },
    { name: 'Nekrum Gutchewer', npcId: 7796 },
    { name: "Shadowpriest Sezz'ziz", npcId: 7275 },
    { name: 'Sergeant Bly', npcId: 7604 },
    { name: 'Hydromancer Velratha', npcId: 7795 },
    { name: "Gahz'rilla", npcId: 7273 },
    { name: 'Chief Ukorz Sandscalp', npcId: 7267 },
    { name: 'Ruuzlu', npcId: 7797 },
  ],
  mara: [
    { name: 'Noxxion', npcId: 13282 },
    { name: 'Razorlash', npcId: 12258 },
    { name: 'Lord Vyletongue', npcId: 12236 },
    { name: 'Celebras the Cursed', npcId: 12225 },
    { name: 'Meshlok the Harvester', npcId: 12237, rare: true },
    { name: 'Tinkerer Gizlock', npcId: 13601 },
    { name: 'Landslide', npcId: 12203 },
    { name: 'Rotgrip', npcId: 13596 },
    { name: 'Princess Theradras', npcId: 12201 },
  ],
  st: [
    { name: "Atal'alarion", npcId: 8580 },
    { name: "Atal'ai Defenders", event: true, bosses: [
      { name: 'Gasher', npcId: 5713 },
      { name: 'Hukku', npcId: 5715 },
      { name: 'Loro', npcId: 5714 },
      { name: 'Mijan', npcId: 5717 },
      { name: 'Zolo', npcId: 5712 },
      { name: 'Zullor', npcId: 5716 },
    ]},
    { name: 'Dreamscythe', npcId: 5721 },
    { name: 'Weaver', npcId: 5720 },
    { name: 'Hazzas', npcId: 5722 },
    { name: 'Morphaz', npcId: 5719 },
    { name: "Jammal'an the Prophet", npcId: 5710 },
    { name: 'Ogom the Wretched', npcId: 5711 },
    { name: 'Avatar of Hakkar', npcId: 8443 },
    { name: 'Shade of Eranikus', npcId: 5709 },
  ],
  brd: [
    { name: 'High Interrogator Gerstahn', npcId: 9018 },
    { name: 'Houndmaster Grebmar', npcId: 9319 },
    { name: 'Lord Roccor', npcId: 9025 },
    { name: 'Ring of Law', event: true, bosses: [
      { name: "Anub'shiah", npcId: 9031 },
      { name: 'Eviscerator', npcId: 9029 },
      { name: 'Grizzle', npcId: 9028 },
      { name: 'Gorosh the Dervish', npcId: 9027 },
      { name: "Ok'thor the Breaker", npcId: 9030 },
      { name: 'Hedrum the Creeper', npcId: 9032 },
    ]},
    {name: 'Pyromancer Loregrain', npcId: 9024},
    { name: 'The Vault', event: true, bosses: [
      { name: 'Dark Keeper Bethek', npcId: 9438 },
      { name: 'Dark Keeper Ofgut', npcId: 9442 },
      { name: 'Dark Keeper Pelver', npcId: 9443 },
      { name: 'Dark Keeper Uggel', npcId: 9439 },
      { name: 'Dark Keeper Vorfalk', npcId: 9437 },
      { name: 'Dark Keeper Zimrel', npcId: 9441 },
    ]},
    { name: 'Lord Incendius', npcId: 9017 },
    { name: 'Warder Stilgiss', npcId: 9041 },
    { name: 'Verek', npcId: 9042 },
    { name: 'Watchman Doomgrip', npcId: 9476 },
    { name: 'Fineous Darkvire', npcId: 9056 },
    { name: "Bael'Gar", npcId: 9016 },
    { name: 'General Angerforge', npcId: 9033 },
    { name: 'Golem Lord Argelmach', npcId: 8983 },
    { name: 'Hurley Blackbreath', npcId: 9537 },
    { name: 'Phalanx', npcId: 9502 },
    { name: 'Plugger Spazzring', npcId: 9499 },
    { name: 'Ribbly Screwspigot', npcId: 9543 },
    { name: 'Ambassador Flamelash', npcId: 9156 },
    { name: 'Panzor the Invincible', npcId: 8923, rare: true },
    { name: 'The Seven', event: true, bosses: [
      { name: 'Haterel', npcId: 9034 },
      { name: 'Angerrel', npcId: 9035 },
      { name: 'Vilerel', npcId: 9036 },
      { name: 'Gloomrel', npcId: 9037 },
      { name: 'Seethrel', npcId: 9038 },
      { name: 'Doomrel', npcId: 9039 },
      { name: 'Doperel', npcId: 9040 },
    ]},
    { name: 'Magmus', npcId: 9938 },
    { name: 'Princess Moira Bronzebeard', npcId: 8929 },
    { name: 'Emperor Dagran Thaurissan', npcId: 9019 },
  ],
  lbrs: [
    { name: 'Burning Felguard', npcId: 10263, rare: true },
    { name: 'Highlord Omokk', npcId: 9196 },
    { name: 'Spirestone Battle Lord', npcId: 9218, rare: true },
    { name: 'Spirestone Lord Magus', npcId: 9217, rare: true },
    { name: "Shadow Hunter Vosh'gajin", npcId: 9236 },
    { name: 'War Master Voone', npcId: 9237 },
    { name: 'Bannok Grimaxe', npcId: 9596, rare: true },
    { name: 'Mother Smolderweb', npcId: 10596 },
    { name: 'Crystal Fang', npcId: 10376, rare: true },
    { name: 'Urok Doomhowl', npcId: 10584 },
    { name: 'Quartermaster Zigris', npcId: 9736 },
    { name: 'Halycon', npcId: 10220 },
    { name: 'Gizrul the Slavener', npcId: 10268 },
    { name: 'Ghok Bashguud', npcId: 9718, rare: true },
    { name: 'Spirestone Butcher', npcId: 9219, rare: true },
    { name: 'Overlord Wyrmthalak', npcId: 9568 },
  ],
  ubrs: [
    { name: 'Pyroguard Emberseer', npcId: 9816 },
    { name: 'Solakar Flamewreath', npcId: 10264 },
    { name: 'Goraluk Anvilcrack', npcId: 10899 },
    { name: 'Jed Runewatcher', npcId: 10509, rare: true },
    { name: 'Gyth', npcId: 10339 },
    { name: 'Warchief Rend Blackhand', npcId: 10429 },
    { name: 'The Beast', npcId: 10430 },
    { name: 'General Drakkisath', npcId: 10363 },
  ],
  dm: [
    { section: 'East' },
    { name: 'Pusillin', npcId: 14354 },
    { name: 'Zevrim Thornhoof', npcId: 11490 },
    { name: 'Hydrospawn', npcId: 13280 },
    { name: 'Lethtendris', npcId: 14327 },
    { name: 'Alzzin the Wildshaper', npcId: 11492 },
    { section: 'West' },
    { name: 'Tendris Warpwood', npcId: 11489 },
    { name: 'Tsuzee', npcId: 11467 },
    { name: 'Illyanna Ravenoak', npcId: 11488 },
    { name: 'Magister Kalendris', npcId: 11487 },
    { name: "Immol'thar", npcId: 11496 },
    { name: 'Lord Helnurath', npcId: 14506 },
    { name: 'Prince Tortheldrin', npcId: 11486 },
    { section: 'North' },
    { name: "Guard Mol'dar", npcId: 14326 },
    { name: 'Stomper Kreeg', npcId: 14322 },
    { name: 'Guard Fengus', npcId: 14321 },
    { name: "Guard Slip'kik", npcId: 14323 },
    { name: 'Captain Kromcrush', npcId: 14325 },
    { name: "Cho'Rush the Observer", npcId: 14324 },
    { name: 'King Gordok', npcId: 11501 },
  ],
  scholo: [
    { name: 'Blood Steward of Kirtonos', npcId: 14861 },
    { name: 'Kirtonos the Herald', npcId: 10506 },
    { name: 'Jandice Barov', npcId: 10503 },
    { name: 'Rattlegore', npcId: 11622 },
    { name: 'Death Knight Darkreaver', npcId: 14516 },
    { name: 'Marduk Blackpool', npcId: 10433 },
    { name: 'Vectus', npcId: 10432 },
    { name: 'Ras Frostwhisper', npcId: 10508 },
    { name: 'Doctor Theolen Krastinov', npcId: 11261 },
    { name: 'Lorekeeper Polkelt', npcId: 10901 },
    { name: 'Instructor Malicia', npcId: 10505 },
    { name: 'Lord Alexei Barov', npcId: 10504 },
    { name: 'Lady Illucia Barov', npcId: 10502 },
    { name: 'The Ravenian', npcId: 10507 },
    { name: 'Darkmaster Gandling', npcId: 1853 },
  ],
  strath: [
    { section: 'Live Side' },
    { name: 'Stratholme Courier', npcId: 11082 },
    { name: 'Hearthsinger Forresten', npcId: 10558 },
    { name: 'Ezra Grimm', npcId: 11058 },
    { name: 'Skul', npcId: 10393 },
    { name: 'Postmaster Malown', npcId: 11143 },
    { name: 'The Unforgiven', npcId: 10516 },
    { name: 'Timmy the Cruel', npcId: 10808 },
    { name: 'Archivist Galford', npcId: 10811 },
    { name: 'Malor the Zealous', npcId: 11032 },
    { name: 'Crimson Hammersmith', npcId: 11120 },
    { name: 'Cannon Master Willey', npcId: 10997 },
    { name: 'Grand Crusader Dathrohan', npcId: 10812 },
    { name: 'Balnazzar', npcId: 10813 },
    { section: 'Undead Side' },
    { name: 'Stonespine', npcId: 10809, rare: true },
    { name: 'Black Guard Swordsmith', npcId: 11121 },
    { name: "Nerub'enkan", npcId: 10437 },
    { name: 'Maleki the Pallid', npcId: 10438 },
    { name: 'Baroness Anastari', npcId: 10436 },
    { name: 'Magistrate Barthilas', npcId: 10435 },
    { name: 'Ramstein the Gorger', npcId: 10439 },
    { name: 'Baron Rivendare', npcId: 10440 },
  ],
};

// ═══════════════════════════════════════
//  WOWHEAD STRATEGY GUIDE URLS
// ═══════════════════════════════════════
const STRATEGY_URLS = {
  rfc:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/ragefire-chasm-dungeon-strategy-wow-classic' }],
  wc:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/wailing-caverns-dungeon-strategy-wow-classic' }],
  deadmines: [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/deadmines-dungeon-strategy-wow-classic' }],
  sfk:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/shadowfang-keep-dungeon-strategy-wow-classic' }],
  stockades: [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/the-stockade-dungeon-strategy-wow-classic' }],
  bfd:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/blackfathom-deeps-dungeon-strategy-wow-classic' }],
  gnomer:    [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/gnomeregan-dungeon-strategy-wow-classic' }],
  rfk:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/razorfen-kraul-dungeon-strategy-wow-classic' }],
  sm:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/scarlet-monastery-dungeon-strategy-wow-classic' }],
  rfd:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/razorfen-downs-dungeon-strategy-wow-classic' }],
  uldaman:   [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/uldaman-dungeon-strategy-wow-classic' }],
  zf:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/zulfarrak-dungeon-strategy-wow-classic' }],
  mara:      [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/maraudon-dungeon-strategy-wow-classic' }],
  st:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/temple-of-atalhakkar-sunken-temple-dungeon-strategy-wow-classic' }],
  brd:       [
    { label: 'Detention Block',  url: 'https://www.wowhead.com/classic/guide/blackrock-depths-detention-block-dungeon-strategy-wow-classic' },
    { label: 'Shadowforge City', url: 'https://www.wowhead.com/classic/guide/blackrock-depths-shadowforge-city-dungeon-strategy-wow-classic' },
  ],
  lbrs:      [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/lower-blackrock-spire-lbrs-dungeon-strategy-wow-classic' }],
  ubrs:      [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/upper-blackrock-spire-ubrs-dungeon-strategy-wow-classic' }],
  dm:        [
    { label: 'East Wing',  url: 'https://www.wowhead.com/classic/guide/dire-maul-east-dungeon-strategy-wow-classic' },
    { label: 'West Wing',  url: 'https://www.wowhead.com/classic/guide/dire-maul-west-dungeon-strategy-wow-classic' },
    { label: 'North Wing', url: 'https://www.wowhead.com/classic/guide/dire-maul-north-dungeon-strategy-wow-classic' },
  ],
  scholo:    [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/scholomance-dungeon-strategy-wow-classic' }],
  strath:    [
    { label: 'Live Side',   url: 'https://www.wowhead.com/classic/guide/stratholme-live-dungeon-strategy-wow-classic' },
    { label: 'Undead Side', url: 'https://www.wowhead.com/classic/guide/stratholme-undead-dungeon-strategy-wow-classic' },
  ],
};

// ═══════════════════════════════════════
//  YOUTUBE VIDEO GUIDES
// ═══════════════════════════════════════
const VIDEO_GUIDES = {
  rfc:       [{ label: 'Guide', youtubeId: 'kmK5CP37rCo' }],
  wc:        [{ label: 'Guide', youtubeId: 'd4ZsTWyeZ14' }],
  deadmines: [{ label: 'Guide', youtubeId: 'OJwHyhfqeOs' }],
  sfk:       [{ label: 'Guide', youtubeId: 'xKVXwRonM7M' }],
  bfd:       [{ label: 'Guide', youtubeId: 'u8ujWkUCIo0' }],
  stockades: [{ label: 'Guide', youtubeId: 'Bik80wgNQAI' }],
  rfk:       [{ label: 'Guide', youtubeId: 'lDlZjWLbdbU' }],
  gnomer:    [{ label: 'Guide', youtubeId: '25qzwh7pkDg' }],
  rfd:       [{ label: 'Guide', youtubeId: 'Dl4KxA7rORE' }],
  sm:        [{ label: 'Guide', youtubeId: '0_UW6a6Hr28' }],
  uldaman:   [{ label: 'Guide', youtubeId: 'fHu6lBF04bg' }],
  zf:        [{ label: 'Guide', youtubeId: 'KSE5CSMKWhg' }],
  mara:      [{ label: 'Guide', youtubeId: 'um3d4wdd4Ag' }],
  st:        [{ label: 'Guide', youtubeId: '45GIKTF9Cu4' }],
  brd:       [{ label: 'Guide', youtubeId: 'AUq-Tb7rZTY' }],
  lbrs:      [{ label: 'Guide', youtubeId: '3bKwDcQqINM' }],
  ubrs:      [{ label: 'Guide', youtubeId: '8CZ6rip-EDY' }],
  scholo:    [{ label: 'Guide', youtubeId: 'xnLVACle1pA' }],
  strath:    [
    { label: 'Live Side',   youtubeId: 'tCwpCbnSWE4' },
    { label: 'Undead Side', youtubeId: '0ztg4Lqjwhs' },
  ],
  dm:        [
    { label: 'East Wing',  youtubeId: 'B9De6Aq4aFs' },
    { label: 'North Wing', youtubeId: 'tTv56xrIkzM' },
    { label: 'West Wing',  youtubeId: '2ha9O7PQ2u8' },
  ],
};

// ═══════════════════════════════════════
//  ZONE MAP IDS  (Wowhead area table IDs)
// ═══════════════════════════════════════
const ZONE_IDS = {
  // Capital cities
  'Orgrimmar': 1637, 'Thunder Bluff': 1638, 'Undercity': 1497,
  'Darnassus': 1657, 'Ironforge': 1537, 'Stormwind City': 1519,
  // Kalimdor
  'Durotar': 1411, 'The Barrens': 17, 'Mulgore': 215,
  'Darkshore': 148, 'Ashenvale': 331, 'Stonetalon Mountains': 406,
  'Desolace': 405, 'Feralas': 357, 'Dustwallow Marsh': 15,
  'Thousand Needles': 400, 'Tanaris': 440, "Un'Goro Crater": 490,
  'Azshara': 16, 'Felwood': 361, 'Winterspring': 618,
  'Moonglade': 493, 'Silithus': 1377,
  // Eastern Kingdoms
  'Dun Morogh': 1, 'Loch Modan': 38, 'Wetlands': 11,
  'Arathi Highlands': 45, 'The Hinterlands': 47,
  'Western Plaguelands': 28, 'Eastern Plaguelands': 139,
  'Tirisfal Glades': 85, 'Silverpine Forest': 130,
  'Hillsbrad Foothills': 267, 'Alterac Mountains': 36,
  'Elwynn Forest': 12, 'Westfall': 40, 'Redridge Mountains': 44,
  'Duskwood': 10, 'Stranglethorn Vale': 33, 'Swamp of Sorrows': 8,
  'Badlands': 3, 'Searing Gorge': 51, 'Burning Steppes': 46,
  'Blasted Lands': 4,
  // Dungeons – Kalimdor
  'Ragefire Chasm': 2437, 'Wailing Caverns': 718,
  'Blackfathom Deeps': 719, 'Razorfen Kraul': 1462,
  'Razorfen Downs': 1463, "Zul'Farrak": 1176,
  'Maraudon': 2100, "The Temple of Atal'Hakkar": 1477,
  'Dire Maul': 2557,
  // Dungeons – Eastern Kingdoms
  'The Deadmines': 1581, 'Shadowfang Keep': 209,
  'The Stockade': 717, 'Gnomeregan': 721,
  'Scarlet Monastery': 796, 'Uldaman': 1337,
  'Blackrock Depths': 1584, 'Blackrock Spire': 1583, 'Lower Blackrock Spire': 1583, 'Upper Blackrock Spire': 1583,
  'Blackrock Mountain': 1265, 'Scholomance': 2057,
  'Stratholme': 2017,
};

// ═══════════════════════════════════════
//  DUNGEON INSTANCE MAP NAMES
//  Maps dungeon ID → ZONE_IDS key so the map modal can open the instance map
// ═══════════════════════════════════════
const DUNGEON_MAP_NAME = {
  rfc:       'Ragefire Chasm',
  wc:        'Wailing Caverns',
  deadmines: 'The Deadmines',
  sfk:       'Shadowfang Keep',
  stockades: 'The Stockade',
  bfd:       'Blackfathom Deeps',
  gnomer:    'Gnomeregan',
  rfk:       'Razorfen Kraul',
  sm:        'Scarlet Monastery',
  rfd:       'Razorfen Downs',
  uldaman:   'Uldaman',
  zf:        "Zul'Farrak",
  mara:      'Maraudon',
  st:        "The Temple of Atal'Hakkar",
  brd:       'Blackrock Depths',
  lbrs:      'Lower Blackrock Spire',
  ubrs:      'Upper Blackrock Spire',
  dm:        'Dire Maul',
  scholo:    'Scholomance',
  strath:    'Stratholme',
};

// ═══════════════════════════════════════
//  MULTI-LEVEL MAPS
// ═══════════════════════════════════════
const MULTI_LEVEL_MAPS = {
  // Keyed by zone ID
  // Burning Steppes is shown as a multi-zone view: the open zone plus the
  // Blackrock Mountain interior, since BRD/LBRS/UBRS all live inside the mountain.
  46: [
    { label: 'Burning Steppes',    src: 'assets/maps/46.jpg'   },
    { label: 'Blackrock Mountain', src: 'assets/maps/1265.jpg' },
  ],
  209: [
    { label: 'The Courtyard',          src: 'assets/maps/209_courtyard.jpg'  },
    { label: 'Dining Hall',            src: 'assets/maps/209_kitchen.jpg'    },
    { label: 'The Vacant Den',         src: 'assets/maps/209_jail.jpg'       },
    { label: 'The Wall Walk',          src: 'assets/maps/209_courtyard1f.jpg'},
    { label: "Lower Observatory",      src: 'assets/maps/209_fenrus.jpg'     },
    { label: "Upper Observatory",      src: 'assets/maps/209_fenrus1f.jpg'   },
    { label: "Arugal Chamber",         src: 'assets/maps/209_nandos.jpg'     },
  ],
  719: [
    { label: "The Pool of Ask'ar",     src: 'assets/maps/719_pool.jpg'       },
    { label: 'Moonshrine Sanctum',     src: 'assets/maps/719_moonshrine.jpg' },
    { label: 'The Forgotten Pool',     src: 'assets/maps/719_forgotten.jpg'  },
  ],
  721: [
    { label: 'Outside Entrance',       src: 'assets/maps/721_outside.jpg' },
    { label: 'The Hall of Gears',      src: 'assets/maps/721_level1.jpg'  },
    { label: 'The Dormitory',          src: 'assets/maps/721_level2.jpg'  },
    { label: 'Launch Bay',             src: 'assets/maps/721_level3.jpg'  },
    { label: 'Tinkers\' Court',        src: 'assets/maps/721_level4.jpg'  },
  ],
  796: [
    { label: 'Graveyard', src: 'assets/maps/796_graveyard.jpg' },
    { label: 'Library',   src: 'assets/maps/796_library.jpg'   },
    { label: 'Armory',    src: 'assets/maps/796_armory.jpg'    },
    { label: 'Cathedral', src: 'assets/maps/796_cathedral.jpg' },
  ],
  1337: [
    { label: 'Excavation Exterior', src: 'assets/maps/1337_exterior.jpg' },
    { label: 'Ruins',               src: 'assets/maps/1337_ruins.jpg'    },
    { label: "Khaz'goroth's Seat",  src: 'assets/maps/1337_seat.jpg'     },
  ],
  1581: [
    { label: 'DeadMines', src: 'assets/maps/1581_cave.jpg' },
    { label: 'Ironclad Cove',          src: 'assets/maps/1581_boat.jpg' },
  ],
  1583: [
    { label: 'Hall of Blackhand',  src: 'assets/maps/1583_hallofblackhand.jpg' },
    { label: 'Hordemar City',      src: 'assets/maps/1583_hordemar.jpg'        },
    { label: 'Skitterweb Tunnels', src: 'assets/maps/1583_skitterweb.jpg'      },
    { label: "Tazz'Alar",         src: 'assets/maps/1583_tazzalor.jpg'        },
    { label: 'Dragonspire Hall',   src: 'assets/maps/1583_dragonspire.jpg'     },
    { label: 'The Rookery',        src: 'assets/maps/1583_rookery.jpg'         },
  ],
  1584: [
    { label: 'Detention Block',  src: 'assets/maps/1584_detention.jpg'   },
    { label: 'Shadowforge City', src: 'assets/maps/1584_shadowforge.jpg' },
  ],
  2017: [
    { label: 'Living Side', src: 'assets/maps/2017_living.jpg' },
    { label: 'Undead Side', src: 'assets/maps/2017_undead.jpg' },
  ],
  2057: [
    { label: 'The Reliquary',        src: 'assets/maps/2057_reliquary.jpg'  },
    { label: 'Chamber of Summoning', src: 'assets/maps/2057_summoning.jpg'  },
    { label: 'The Upper Study',      src: 'assets/maps/2057_upperstudy.jpg' },
    { label: "Headmaster's Study",   src: 'assets/maps/2057_headmaster.jpg' },
  ],
  2100: [
    { label: 'Caverns',           src: 'assets/maps/2100_caverns.jpg'   },
    { label: "Zaetar's Grave",    src: 'assets/maps/2100_zaetars.jpg'   },
    { label: 'The Wicked Grotto', src: 'assets/maps/2100_grotto.jpg'    },
    { label: 'Foulspore Cavern',  src: 'assets/maps/2100_foulspore.jpg' },
  ],
  2557: [
    { label: 'Gordok Commons (North)',                   src: 'assets/maps/2557_gordok.jpg'       },
    { label: 'Capital Gardens (West)',                   src: 'assets/maps/2557_capital.jpg'      },
    { label: 'Court of the Highborne (West)',            src: 'assets/maps/2557_court.jpg'        },
    { label: "Prison of Immol'thar (West)",              src: 'assets/maps/2557_prison.jpg'       },
    { label: 'Warpwood Quarter (East)',                  src: 'assets/maps/2557_warpwood.jpg'     },
    { label: 'Conservatory & Shrine of Eldretharr (East)', src: 'assets/maps/2557_conservatory.jpg' },
  ],
  // Keyed by location name (for dungeons sharing a zone ID)
  'Lower Blackrock Spire': [
    { label: 'Hall of Blackhand',  src: 'assets/maps/1583_hallofblackhand.jpg' },
    { label: 'Hordemar City',      src: 'assets/maps/1583_hordemar.jpg'        },
    { label: 'Skitterweb Tunnels', src: 'assets/maps/1583_skitterweb.jpg'      },
    { label: "Tazz'Alar",          src: 'assets/maps/1583_tazzalor.jpg'        },
    { label: 'Dragonspire Hall',   src: 'assets/maps/1583_dragonspire.jpg'     },
    { label: 'The Rookery',        src: 'assets/maps/1583_rookery.jpg'         },
  ],
  'Upper Blackrock Spire': [
    { label: 'Dragonspire Hall',  src: 'assets/maps/ubrs_dragonspire.jpg' },
    { label: 'The Rookery',       src: 'assets/maps/ubrs_rookery.jpg'     },
    { label: 'Blackrock Stadium', src: 'assets/maps/ubrs_stadium.jpg'     },
  ],
  // Combined view for quests that reference "Blackrock Spire" without specifying lower/upper
  'Blackrock Spire': [
    { label: 'Lower – Hall of Blackhand',  src: 'assets/maps/1583_hallofblackhand.jpg' },
    { label: 'Lower – Hordemar City',      src: 'assets/maps/1583_hordemar.jpg'        },
    { label: 'Lower – Skitterweb Tunnels', src: 'assets/maps/1583_skitterweb.jpg'      },
    { label: "Lower – Tazz'Alar",          src: 'assets/maps/1583_tazzalor.jpg'        },
    { label: 'Lower – Dragonspire Hall',   src: 'assets/maps/1583_dragonspire.jpg'     },
    { label: 'Lower – The Rookery',        src: 'assets/maps/1583_rookery.jpg'         },
    { label: 'Upper – Dragonspire Hall',   src: 'assets/maps/ubrs_dragonspire.jpg'     },
    { label: 'Upper – The Rookery',        src: 'assets/maps/ubrs_rookery.jpg'         },
    { label: 'Upper – Blackrock Stadium',  src: 'assets/maps/ubrs_stadium.jpg'         },
  ],
};

// ═══════════════════════════════════════
//  PREDEFINED MAP PINS
//  Keyed by location name or zone ID (matches ZONE_IDS keys / DUNGEON_MAP_NAME values).
//  For multi-level maps, value is an array-of-arrays indexed by level.
//  For single-level maps, value is a flat array of pins.
//  Pin: { x, y, label, type: 'boss'|'npc'|'quest'|'point'|'dungeon' }
//  Coordinates: 0–100 (0,0 = top-left, 100,100 = bottom-right)
// ═══════════════════════════════════════
const MAP_PINS = {
  // Dungeon-entrance pins, placed on each dungeon's outdoor location zone map
  // (keyed by the dungeon's `location`). Labels use the dungeon map names.
  'Orgrimmar':           [{ x: 50, y: 52, label: 'Ragefire Chasm',            type: 'dungeon' }],
  'The Barrens': [
    { x: 46, y: 35, label: 'Wailing Caverns',  type: 'dungeon' },
    { x: 42, y: 89, label: 'Razorfen Kraul',   type: 'dungeon' },
    { x: 50, y: 92, label: 'Razorfen Downs',   type: 'dungeon' },
  ],
  'Westfall':            [{ x: 42, y: 72, label: 'The Deadmines',             type: 'dungeon' }],
  'Silverpine Forest':   [{ x: 42, y: 67, label: 'Shadowfang Keep',          type: 'dungeon' }],
  'Ashenvale':           [{ x: 14, y: 13, label: 'Blackfathom Deeps',        type: 'dungeon' }],
  'Stormwind City':      [{ x: 41, y: 56, label: 'The Stockade',             type: 'dungeon' }],
  'Dun Morogh':          [{ x: 23, y: 39, label: 'Gnomeregan',               type: 'dungeon' }],
  'Tirisfal Glades':     [{ x: 84, y: 33, label: 'Scarlet Monastery',        type: 'dungeon' }],
  'Badlands':            [{ x: 42, y: 12, label: 'Uldaman',                   type: 'dungeon' }],
  'Tanaris':             [{ x: 39, y: 20, label: "Zul'Farrak",               type: 'dungeon' }],
  'Desolace':            [{ x: 29, y: 58, label: 'Maraudon',                  type: 'dungeon' }],
  'Swamp of Sorrows':    [{ x: 70, y: 53, label: "The Temple of Atal'Hakkar", type: 'dungeon' }],
  'Feralas':             [{ x: 58, y: 42, label: 'Dire Maul',                type: 'dungeon' }],
  'Western Plaguelands': [{ x: 69, y: 75, label: 'Scholomance',              type: 'dungeon' }],
  'Eastern Plaguelands': [{ x: 30, y: 10, label: 'Stratholme',               type: 'dungeon' }],
  // Burning Steppes is a multi-level map (level 0: Burning Steppes,
  // level 1: Blackrock Mountain interior, zone 1265). BRD/LBRS/UBRS
  // entrances sit on the Blackrock Mountain floor.
  'Burning Steppes': [
    [   // level 0 — Burning Steppes (entrance into Blackrock Mountain)
      { x: 29, y: 38, label: 'BRD \\ LBRS \\ UBRS', type: 'dungeon' },
    ],
    [   // level 1 — Blackrock Mountain (1265)
      { x: 24, y: 13, label: 'Blackrock Depths',      type: 'dungeon' },
      { x: 82, y: 44, label: 'Lower Blackrock Spire', type: 'dungeon' },
      { x: 79, y: 33, label: 'Upper Blackrock Spire', type: 'dungeon' },
    ],
  ],
};
