// ═══════════════════════════════════════
//  BOSS ENCOUNTERS
//  Each entry: { name, npcId } | { name, npcId, rare: true } | { section } | { name, npcId: null } for events
// ═══════════════════════════════════════
const BOSS_ENCOUNTERS = {
  rfc: [
    { name: 'Oggleflint', npcId: 11517 },
    { name: 'Taragaman the Hungerer', npcId: 11520 },
    { name: 'Jergosh the Invoker', npcId: 11518 },
    { name: 'Bazzalan', npcId: 11519 },
  ],
  wc: [
    { name: 'Kresh', npcId: 3653 },
    { name: 'Skum', npcId: 3674 },
    { name: 'Deviate Faerie Dragon', npcId: 5912, rare: true },
    { name: 'Lady Anacondra', npcId: 3671 },
    { name: 'Lord Cobrahn', npcId: 3669 },
    { name: 'Lord Pythas', npcId: 3670 },
    { name: 'Lord Serpentis', npcId: 3673 },
    { name: 'Verdan the Everliving', npcId: 5775 },
    { name: 'Mutanus the Devourer', npcId: 3654 },
  ],
  deadmines: [
    { name: "Rhahk'Zor", npcId: 644 },
    { name: 'Miner Johnson', npcId: 3586, rare: true },
    { name: "Sneed's Shredder", npcId: 643 },
    { name: 'Gilnid', npcId: 1763 },
    { name: 'Mr. Smite', npcId: 646 },
    { name: 'Captain Greenskin', npcId: 647 },
    { name: 'Cookie', npcId: 645 },
    { name: 'Edwin VanCleef', npcId: 639 },
  ],
  sfk: [
    { name: 'Rethilgore', npcId: 3914 },
    { name: 'Razorclaw the Butcher', npcId: 3886 },
    { name: 'Baron Silverlaine', npcId: 3887 },
    { name: 'Commander Springvale', npcId: 4278 },
    { name: 'Odo the Blindwatcher', npcId: 4279 },
    { name: 'Deathsworn Captain', npcId: 3872, rare: true },
    { name: 'Fenrus the Devourer', npcId: 4274 },
    { name: 'Wolf Master Nandos', npcId: 3927 },
    { name: 'Archmage Arugal', npcId: 4275 },
  ],
  stockades: [
    { name: 'Targorr the Dread', npcId: 1696 },
    { name: 'Kam Deepfury', npcId: 1666 },
    { name: 'Hamhock', npcId: 1717 },
    { name: 'Bazil Thredd', npcId: 1716 },
    { name: 'Dextren Ward', npcId: 1663 },
    { name: 'Bruegal Ironknuckle', npcId: 1720, rare: true },
  ],
  bfd: [
    { name: 'Ghamoo-Ra', npcId: 4887 },
    { name: 'Lady Sarevess', npcId: 4831 },
    { name: 'Gelihast', npcId: 6243 },
    { name: 'Lorgus Jett', npcId: 12902 },
    { name: 'Twilight Lord Kelris', npcId: 4832 },
    { name: "Old Serra'kis", npcId: 4830 },
    { name: "Aku'mai", npcId: 4829 },
    { section: 'Horde Only' },
    { name: 'Baron Aquanis', npcId: 12876 },
  ],
  gnomer: [
    { name: 'Grubbis', npcId: 7361 },
    { name: 'Viscous Fallout', npcId: 7079 },
    { name: 'Electrocutioner 6000', npcId: 6235 },
    { name: 'Crowd Pummeler 9-60', npcId: 6229 },
    { name: 'Dark Iron Ambassador', npcId: 6228, rare: true },
    { name: 'Mekgineer Thermaplugg', npcId: 7800 },
  ],
  rfk: [
    { name: 'Roogug', npcId: 6168 },
    { name: 'Aggem Thorncurse', npcId: 4424 },
    { name: 'Death Speaker Jargba', npcId: 4428 },
    { name: 'Overlord Ramtusk', npcId: 4420 },
    { name: 'Agathelos the Raging', npcId: 4422 },
    { name: 'Earthcaller Halmgar', npcId: 4842, rare: true },
    { name: 'Blind Hunter', npcId: 4425, rare: true },
    { name: 'Charlga Razorflank', npcId: 4421 },
  ],
  sm: [
    { section: 'Graveyard' },
    { name: 'Interrogator Vishas', npcId: 3983 },
    { name: 'Bloodmage Thalnos', npcId: 4543 },
    { name: 'Azshir the Sleepless', npcId: 6490, rare: true },
    { name: 'Fallen Champion', npcId: 6488, rare: true },
    { name: 'Ironspine', npcId: 6489, rare: true },
    { section: 'Library' },
    { name: 'Houndmaster Loksey', npcId: 3974 },
    { name: 'Arcanist Doan', npcId: 6487 },
    { section: 'Armory' },
    { name: 'Herod', npcId: 3975 },
    { section: 'Cathedral' },
    { name: 'Scarlet Commander Mograine', npcId: 3976 },
    { name: 'High Inquisitor Whitemane', npcId: 3977 },
    { name: 'High Inquisitor Fairbanks', npcId: 4542 },
  ],
  rfd: [
    { name: "Tuten'kash", npcId: 7355 },
    { name: 'Ragglesnout', npcId: 7354, rare: true },
    { name: 'Mordresh Fire Eye', npcId: 7357 },
    { name: 'Glutton', npcId: 8567 },
    { name: 'Plaguemaw the Rotting', npcId: 7356 },
    { name: 'Amnennar the Coldbringer', npcId: 7358 },
  ],
  uldaman: [
    { name: 'Revelosh', npcId: 6910 },
    { name: 'Ironaya', npcId: 7228 },
    { name: 'Obsidian Sentinel', npcId: 7023 },
    { name: 'Ancient Stone Keeper', npcId: 7206 },
    { name: 'Galgann Firehammer', npcId: 7291 },
    { name: 'Grimlok', npcId: 4854 },
    { name: 'Archaedas', npcId: 2748 },
    { section: 'Horde Only' },
    { name: 'Baelog', npcId: 6906 },
    { name: 'Eric the Swift', npcId: 6907 },
    { name: 'Olaf', npcId: 6908 },
  ],
  zf: [
    { name: "Antu'sul", npcId: 8127 },
    { name: 'Theka the Martyr', npcId: 7272 },
    { name: 'Sandarr Dunereaver', npcId: 10080, rare: true },
    { name: 'Sandfury Executioner', npcId: 7274 },
    { name: 'Zerillis', npcId: 10082, rare: true },
    { name: 'Dustwraith', npcId: 10081, rare: true },
    { name: "Witch Doctor Zum'rah", npcId: 7271 },
    { name: 'Nekrum Gutchewer', npcId: 7796 },
    { name: "Shadowpriest Sezz'ziz", npcId: 7275 },
    { name: 'Sergeant Bly', npcId: 7604 },
    { name: 'Hydromancer Velratha', npcId: 7795 },
    { name: "Gahz'rilla", npcId: 7273 },
    { name: 'Chief Ukorz Sandscalp', npcId: 7267 },
    { name: 'Ruuzlu', npcId: 7797 },
  ],
  mara: [
    { name: 'Noxxion', npcId: 13282 },
    { name: 'Razorlash', npcId: 12258 },
    { name: 'Lord Vyletongue', npcId: 12236 },
    { name: 'Celebras the Cursed', npcId: 12225 },
    { name: 'Meshlok the Harvester', npcId: 12237, rare: true },
    { name: 'Tinkerer Gizlock', npcId: 13601 },
    { name: 'Landslide', npcId: 12203 },
    { name: 'Rotgrip', npcId: 13596 },
    { name: 'Princess Theradras', npcId: 12201 },
  ],
  st: [
    { name: "Atal'alarion", npcId: 8580 },
    { name: 'Zolo', npcId: 5712 },
    { name: 'Loro', npcId: 5714 },
    { name: 'Hukku', npcId: 5715 },
    { name: 'Zullor', npcId: 5716 },
    { name: 'Mijan', npcId: 5717 },
    { name: 'Dreamscythe', npcId: 5721 },
    { name: 'Weaver', npcId: 5720 },
    { name: 'Hazzas', npcId: 5722 },
    { name: 'Morphaz', npcId: 5719 },
    { name: "Jammal'an the Prophet", npcId: 5710 },
    { name: 'Ogom the Wretched', npcId: 5711 },
    { name: 'Avatar of Hakkar', npcId: 8443 },
    { name: 'Shade of Eranikus', npcId: 5709 },
  ],
  brd: [
    { name: 'High Interrogator Gerstahn', npcId: 9018 },
    { name: 'Houndmaster Grebmar', npcId: 9319 },
    { name: 'Lord Roccor', npcId: 9025 },
    { name: 'Ring of Law', npcId: null },
    { name: 'The Vault (Dark Keepers)', npcId: null },
    { name: 'Lord Incendius', npcId: 9017 },
    { name: 'Warder Stilgiss', npcId: 9041 },
    { name: 'Verek', npcId: 9042 },
    { name: 'Watchman Doomgrip', npcId: 9476 },
    { name: 'Fineous Darkvire', npcId: 9056 },
    { name: "Bael'Gar", npcId: 9016 },
    { name: 'General Angerforge', npcId: 9033 },
    { name: 'Golem Lord Argelmach', npcId: 8983 },
    { name: 'Hurley Blackbreath', npcId: 9537 },
    { name: 'Phalanx', npcId: 9502 },
    { name: 'Plugger Spazzring', npcId: 9499 },
    { name: 'Ribbly Screwspigot', npcId: 9543 },
    { name: 'Ambassador Flamelash', npcId: 9156 },
    { name: 'Panzor the Invincible', npcId: 8923, rare: true },
    { name: 'The Seven', npcId: null },
    { name: 'Magmus', npcId: 9938 },
    { name: 'Princess Moira Bronzebeard', npcId: 8929 },
    { name: 'Emperor Dagran Thaurissan', npcId: 9019 },
  ],
  lbrs: [
    { name: 'Burning Felguard', npcId: 10263, rare: true },
    { name: 'Highlord Omokk', npcId: 9196 },
    { name: 'Spirestone Battle Lord', npcId: 9218, rare: true },
    { name: 'Spirestone Lord Magus', npcId: 9217, rare: true },
    { name: "Shadow Hunter Vosh'gajin", npcId: 9236 },
    { name: 'War Master Voone', npcId: 9237 },
    { name: 'Bannok Grimaxe', npcId: 9596, rare: true },
    { name: 'Mother Smolderweb', npcId: 10596 },
    { name: 'Crystal Fang', npcId: 10376, rare: true },
    { name: 'Urok Doomhowl', npcId: 10584 },
    { name: 'Quartermaster Zigris', npcId: 9736 },
    { name: 'Halycon', npcId: 10220 },
    { name: 'Gizrul the Slavener', npcId: 10268 },
    { name: 'Ghok Bashguud', npcId: 9718, rare: true },
    { name: 'Spirestone Butcher', npcId: 9219, rare: true },
    { name: 'Overlord Wyrmthalak', npcId: 9568 },
  ],
  ubrs: [
    { name: 'Pyroguard Emberseer', npcId: 9816 },
    { name: 'Solakar Flamewreath', npcId: 10264 },
    { name: 'Goraluk Anvilcrack', npcId: 10899 },
    { name: 'Jed Runewatcher', npcId: 10509, rare: true },
    { name: 'Gyth', npcId: 10339 },
    { name: 'Warchief Rend Blackhand', npcId: 10429 },
    { name: 'The Beast', npcId: 10430 },
    { name: 'General Drakkisath', npcId: 10363 },
  ],
  dm: [
    { section: 'East' },
    { name: 'Zevrim Thornhoof', npcId: 11490 },
    { name: 'Hydrospawn', npcId: 13280 },
    { name: 'Lethtendris', npcId: 14327 },
    { name: 'Alzzin the Wildshaper', npcId: 11492 },
    { section: 'West' },
    { name: 'Tendris Warpwood', npcId: 11489 },
    { name: 'Tsuzee', npcId: 11467 },
    { name: 'Illyanna Ravenoak', npcId: 11488 },
    { name: 'Magister Kalendris', npcId: 11487 },
    { name: "Immol'thar", npcId: 11496 },
    { name: 'Lord Helnurath', npcId: 14506 },
    { name: 'Prince Tortheldrin', npcId: 11486 },
    { section: 'North' },
    { name: "Guard Mol'dar", npcId: 14326 },
    { name: 'Stomper Kreeg', npcId: 14322 },
    { name: 'Guard Fengus', npcId: 14321 },
    { name: "Guard Slip'kik", npcId: 14323 },
    { name: 'Captain Kromcrush', npcId: 14325 },
    { name: "Cho'Rush the Observer", npcId: 14324 },
    { name: 'King Gordok', npcId: 11501 },
  ],
  scholo: [
    { name: 'Blood Steward of Kirtonos', npcId: 14861 },
    { name: 'Kirtonos the Herald', npcId: 10506 },
    { name: 'Jandice Barov', npcId: 10503 },
    { name: 'Rattlegore', npcId: 11622 },
    { name: 'Death Knight Darkreaver', npcId: 14516 },
    { name: 'Marduk Blackpool', npcId: 10433 },
    { name: 'Vectus', npcId: 10432 },
    { name: 'Ras Frostwhisper', npcId: 10508 },
    { name: 'Doctor Theolen Krastinov', npcId: 11261 },
    { name: 'Lorekeeper Polkelt', npcId: 10901 },
    { name: 'Instructor Malicia', npcId: 10505 },
    { name: 'Lady Illucia Barov', npcId: 10502 },
    { name: 'The Ravenian', npcId: 10507 },
    { name: 'Darkmaster Gandling', npcId: 1853 },
  ],
  strath: [
    { section: 'Live Side' },
    { name: 'Stratholme Courier', npcId: 11082 },
    { name: 'Hearthsinger Forresten', npcId: 10558 },
    { name: 'Skul', npcId: 10393 },
    { name: 'Postmaster Malown', npcId: 11143 },
    { name: 'The Unforgiven', npcId: 10516 },
    { name: 'Timmy the Cruel', npcId: 10808 },
    { name: 'Archivist Galford', npcId: 10811 },
    { name: 'Malor the Zealous', npcId: 11032 },
    { name: 'Cannon Master Willey', npcId: 10997 },
    { name: 'Grand Crusader Dathrohan', npcId: 10812 },
    { section: 'Undead Side' },
    { name: 'Stonespine', npcId: 10809, rare: true },
    { name: "Nerub'enkan", npcId: 10437 },
    { name: 'Maleki the Pallid', npcId: 10438 },
    { name: 'Baroness Anastari', npcId: 10436 },
    { name: 'Magistrate Barthilas', npcId: 10435 },
    { name: 'Ramstein the Gorger', npcId: 10439 },
    { name: 'Baron Rivendare', npcId: 10440 },
  ],
};

// ═══════════════════════════════════════
//  WOWHEAD STRATEGY GUIDE URLS
// ═══════════════════════════════════════
const STRATEGY_URLS = {
  rfc:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/ragefire-chasm-dungeon-strategy-wow-classic' }],
  wc:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/wailing-caverns-dungeon-strategy-wow-classic' }],
  deadmines: [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/deadmines-dungeon-strategy-wow-classic' }],
  sfk:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/shadowfang-keep-dungeon-strategy-wow-classic' }],
  stockades: [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/the-stockade-dungeon-strategy-wow-classic' }],
  bfd:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/blackfathom-deeps-dungeon-strategy-wow-classic' }],
  gnomer:    [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/gnomeregan-dungeon-strategy-wow-classic' }],
  rfk:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/razorfen-kraul-dungeon-strategy-wow-classic' }],
  sm:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/scarlet-monastery-dungeon-strategy-wow-classic' }],
  rfd:       [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/razorfen-downs-dungeon-strategy-wow-classic' }],
  uldaman:   [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/uldaman-dungeon-strategy-wow-classic' }],
  zf:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/zulfarrak-dungeon-strategy-wow-classic' }],
  mara:      [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/maraudon-dungeon-strategy-wow-classic' }],
  st:        [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/temple-of-atalhakkar-sunken-temple-dungeon-strategy-wow-classic' }],
  brd:       [
    { label: 'Detention Block',  url: 'https://www.wowhead.com/classic/guide/blackrock-depths-detention-block-dungeon-strategy-wow-classic' },
    { label: 'Shadowforge City', url: 'https://www.wowhead.com/classic/guide/blackrock-depths-shadowforge-city-dungeon-strategy-wow-classic' },
  ],
  lbrs:      [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/lower-blackrock-spire-lbrs-dungeon-strategy-wow-classic' }],
  ubrs:      [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/upper-blackrock-spire-ubrs-dungeon-strategy-wow-classic' }],
  dm:        [
    { label: 'East Wing',  url: 'https://www.wowhead.com/classic/guide/dire-maul-east-dungeon-strategy-wow-classic' },
    { label: 'West Wing',  url: 'https://www.wowhead.com/classic/guide/dire-maul-west-dungeon-strategy-wow-classic' },
    { label: 'North Wing', url: 'https://www.wowhead.com/classic/guide/dire-maul-north-dungeon-strategy-wow-classic' },
  ],
  scholo:    [{ label: 'Strategy Guide', url: 'https://www.wowhead.com/classic/guide/scholomance-dungeon-strategy-wow-classic' }],
  strath:    [
    { label: 'Live Side',   url: 'https://www.wowhead.com/classic/guide/stratholme-live-dungeon-strategy-wow-classic' },
    { label: 'Undead Side', url: 'https://www.wowhead.com/classic/guide/stratholme-undead-dungeon-strategy-wow-classic' },
  ],
};

// ═══════════════════════════════════════
//  ZONE MAP IDS  (Wowhead area table IDs)
// ═══════════════════════════════════════
const ZONE_IDS = {
  // Capital cities
  'Orgrimmar': 1637, 'Thunder Bluff': 1638, 'Undercity': 1497,
  'Darnassus': 1657, 'Ironforge': 1537, 'Stormwind City': 1519,
  // Kalimdor
  'Durotar': 1411, 'The Barrens': 17, 'Mulgore': 215,
  'Darkshore': 148, 'Ashenvale': 331, 'Stonetalon Mountains': 406,
  'Desolace': 405, 'Feralas': 357, 'Dustwallow Marsh': 15,
  'Thousand Needles': 400, 'Tanaris': 440, "Un'Goro Crater": 490,
  'Azshara': 16, 'Felwood': 361, 'Winterspring': 618,
  'Moonglade': 493, 'Silithus': 1377,
  // Eastern Kingdoms
  'Dun Morogh': 1, 'Loch Modan': 38, 'Wetlands': 11,
  'Arathi Highlands': 45, 'The Hinterlands': 47,
  'Western Plaguelands': 28, 'Eastern Plaguelands': 139,
  'Tirisfal Glades': 85, 'Silverpine Forest': 130,
  'Hillsbrad Foothills': 267, 'Alterac Mountains': 36,
  'Elwynn Forest': 12, 'Westfall': 40, 'Redridge Mountains': 44,
  'Duskwood': 10, 'Stranglethorn Vale': 33, 'Swamp of Sorrows': 8,
  'Badlands': 3, 'Searing Gorge': 51, 'Burning Steppes': 46,
  'Blasted Lands': 4,
  // Dungeons – Kalimdor
  'Ragefire Chasm': 2437, 'Wailing Caverns': 718,
  'Blackfathom Deeps': 719, 'Razorfen Kraul': 1462,
  'Razorfen Downs': 1463, "Zul'Farrak": 1176,
  'Maraudon': 2100, "The Temple of Atal'Hakkar": 1477,
  'Dire Maul': 2557,
  // Dungeons – Eastern Kingdoms
  'The Deadmines': 1581, 'Shadowfang Keep': 209,
  'The Stockade': 717, 'Gnomeregan': 721,
  'Scarlet Monastery': 796, 'Uldaman': 1337,
  'Blackrock Depths': 1584, 'Blackrock Spire': 1583,
  'Blackrock Mountain': 1265, 'Scholomance': 2057,
  'Stratholme': 2017,
};

// ═══════════════════════════════════════
//  MULTI-LEVEL MAPS
// ═══════════════════════════════════════
const MULTI_LEVEL_MAPS = {
  1583: [
    { label: 'Level 1',          src: 'assets/maps/1583_1.jpg' },
    { label: 'Level 2',          src: 'assets/maps/1583_2.jpg' },
    { label: 'Level 3',          src: 'assets/maps/1583_3.jpg' },
    { label: 'Level 4',          src: 'assets/maps/1583_4.jpg' },
    { label: 'Level 5 (Part 1)', src: 'assets/maps/1583_5a.jpg' },
    { label: 'Level 5 (Part 2)', src: 'assets/maps/1583_5b.jpg' },
    { label: 'Level 6 (Part 1)', src: 'assets/maps/1583_6a.jpg' },
    { label: 'Level 6 (Part 2)', src: 'assets/maps/1583_6b.jpg' },
    { label: 'Level 7',          src: 'assets/maps/1583_7.jpg' },
  ],
};
