// Atlas Classic instance maps — generated by scraper/dungeon-maps/export_to_app.py. Do not edit by hand.
// Keyed by app location name (see DUNGEON_MAP_NAME in constants.js).
const ATLAS_INSTANCE_MAPS = {
 "Ragefire Chasm": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_RagefireChasm.png",
    "entrance": false,
    "zoneName": "Ragefire Chasm",
    "location": "Orgrimmar",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Oggleflint",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Taragaman the Hungerer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Jergosh the Invoker",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Bazzalan",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Wailing Caverns": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_WailingCavernsEnt.png",
    "entrance": true,
    "zoneName": "Wailing Caverns (Entrance)",
    "location": "The Barrens",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Wailing Caverns",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Mad Magglish",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Trigore the Lasher (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Boahn (Rare)",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_WailingCaverns.png",
    "entrance": false,
    "zoneName": "Wailing Caverns",
    "location": "The Barrens",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Disciple of Naralex",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Lord Cobrahn",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Lady Anacondra",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Kresh",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Lord Pythas",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Skum",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Lord Serpentis",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Verdan the Everliving",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Mutanus the Devourer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Naralex",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Deviate Faerie Dragon (Rare)",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "The Deadmines": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_TheDeadminesEnt.png",
    "entrance": true,
    "zoneName": "The Deadmines (Entrance)",
    "location": "Westfall",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "The Deadmines",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Marisa du'Paige",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Brainwashed Noble (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Foreman Thistlenettle",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_TheDeadmines.png",
    "entrance": false,
    "zoneName": "The Deadmines",
    "location": "Westfall",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Exit",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Rhahk'Zor",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Miner Johnson (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Sneed",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Sneed's Shredder",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Gilnid",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Defias Gunpowder",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Captain Greenskin",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Edwin VanCleef",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Mr. Smite",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Cookie",
      "indent": true,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Shadowfang Keep": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_ShadowfangKeep.png",
    "entrance": false,
    "zoneName": "Shadowfang Keep",
    "location": "Silverpine Forest",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "B-C) Walkway",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Deathsworn Captain (Rare)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Deathstalker Adamant",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Sorcerer Ashcrombe",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Rethilgore",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Razorclaw the Butcher",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Baron Silverlaine",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Commander Springvale",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Odo the Blindwatcher",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Fenrus the Devourer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Wolf Master Nandos",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Archmage Arugal",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Fel Steed",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Jordan's Hammer",
      "indent": true,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Blackfathom Deeps": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_BlackfathomDeepsEnt.png",
    "entrance": true,
    "zoneName": "Blackfathom Deeps (Entrance)",
    "location": "Ashenvale",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Blackfathom Deeps",
      "indent": false,
      "category": "location"
     }
    ]
   },
   {
    "label": "Upper",
    "src": "assets/maps/atlas/CL_BlackfathomDeepsA.png",
    "entrance": false,
    "zoneName": "Blackfathom DeepsMapA",
    "location": "Ashenvale",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Ghamoo-ra",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Lorgalis Manuscript",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Lady Sarevess",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Argent Guard Thaelrid",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Gelihast",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Lorgus Jett",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Middle",
    "src": "assets/maps/atlas/CL_BlackfathomDeepsB.png",
    "entrance": false,
    "zoneName": "Blackfathom DeepsMapB",
    "location": "Ashenvale",
    "pois": [
     {
      "ref": "6",
      "label": "Lorgus Jett",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Baron Aquanis",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Fathom Core",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Twilight Lord Kelris",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Aku'mai",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Lower",
    "src": "assets/maps/atlas/CL_BlackfathomDeepsC.png",
    "entrance": false,
    "zoneName": "Blackfathom DeepsMapC",
    "location": "Ashenvale",
    "pois": [
     {
      "ref": "9",
      "label": "Old Serra'kis",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "The Stockade": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_TheStockade.png",
    "entrance": false,
    "zoneName": "The Stockade",
    "location": "Stormwind City",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Targorr the Dread",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Kam Deepfury",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Hamhock",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Bazil Thredd",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Dextren Ward",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Bruegal Ironknuckle (Rare)",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Gnomeregan": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_GnomereganEnt.png",
    "entrance": true,
    "zoneName": "Gnomeregan (Entrance)",
    "location": "Dun Morogh",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Meeting Stone",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Gnomeregan (Front)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Gnomeregan (Back)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Elevator",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Transpolyporter",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Sprok <Away Team>",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Matrix Punchograph 3005-A",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Namdo Bizzfizzle <Engineering Supplies>",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Techbot",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_Gnomeregan.png",
    "entrance": false,
    "zoneName": "Gnomeregan",
    "location": "Dun Morogh",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance (Front)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Entrance (Back)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Blastmaster Emi Shortfuse",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Grubbis",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Chomper",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "The Clean Zone",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Tink Sprocketwhistle <Engineering Supplies>",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "The Sparklematic 5200",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Mail Box",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Kernobee",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Alarm-a-bomb 2600",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Matrix Punchograph 3005-B",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Viscous Fallout",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Electrocutioner 6000",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Matrix Punchograph 3005-C",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Crowd Pummeler 9-60",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Matrix Punchograph 3005-D",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Dark Iron Ambassador",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Mekgineer Thermaplugg",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Razorfen Kraul": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_RazorfenKraul.png",
    "entrance": false,
    "zoneName": "Razorfen Kraul",
    "location": "The Barrens",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Roogug",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Aggem Thorncurse",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Death Speaker Jargba",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Overlord Ramtusk",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Agathelos the Raging",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Blind Hunter (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Charlga Razorflank",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Willix the Importer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Heralath Fallowbrook",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Earthcaller Halmgar (Rare)",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Scarlet Monastery": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_ScarletMonasteryEnt.png",
    "entrance": true,
    "zoneName": "Scarlet Monastery (Entrance)",
    "location": "Tirisfal Glades",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Graveyard",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Cathedral",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "D",
      "label": "Armory",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "E",
      "label": "Library",
      "indent": false,
      "category": "location"
     }
    ]
   },
   {
    "label": "Graveyard",
    "src": "assets/maps/atlas/CL_SMGraveyard.png",
    "entrance": false,
    "zoneName": "Scarlet Monastery: Graveyard",
    "location": "Tirisfal Glades",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Interrogator Vishas",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Vorrel Sengutz",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Ironspine (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Azshir the Sleepless (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Fallen Champion (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Bloodmage Thalnos",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Library",
    "src": "assets/maps/atlas/CL_SMLibrary.png",
    "entrance": false,
    "zoneName": "Scarlet Monastery: Library",
    "location": "Tirisfal Glades",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Houndmaster Loksey",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Arcanist Doan",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Armory",
    "src": "assets/maps/atlas/CL_SMArmory.png",
    "entrance": false,
    "zoneName": "Scarlet Monastery: Armory",
    "location": "Tirisfal Glades",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Herod",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Cathedral",
    "src": "assets/maps/atlas/CL_SMCathedral.png",
    "entrance": false,
    "zoneName": "Scarlet Monastery: Cathedral",
    "location": "Tirisfal Glades",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "High Inquisitor Fairbanks",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Scarlet Commander Mograine",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "High Inquisitor Whitemane",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Razorfen Downs": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_RazorfenDowns.png",
    "entrance": false,
    "zoneName": "Razorfen Downs",
    "location": "The Barrens",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Tuten'kash",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Henry Stern",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Belnistrasz",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Mordresh Fire Eye",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Glutton",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Ragglesnout (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Amnennar the Coldbringer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Plaguemaw the Rotting",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Uldaman": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_UldamanEnt.png",
    "entrance": true,
    "zoneName": "Uldaman (Entrance)",
    "location": "Badlands",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Uldaman",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Hammertoe Grez",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Magregan Deepshadow",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Tablet of Ryun'Eh",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Krom Stoutarm's Chest",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Garrett Family Chest",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "1') Digmaster Shovelphlange (Rare)",
      "indent": false,
      "category": "green"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_Uldaman.png",
    "entrance": false,
    "zoneName": "Uldaman",
    "location": "Badlands",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance (Front)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Entrance (Back)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Baelog",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Eric \"The Swift\"",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Olaf",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Baelog's Chest",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Conspicuous Urn",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Remains of a Paladin",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Revelosh",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Ironaya",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Obsidian Sentinel",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Annora <Master Enchanter>",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Ancient Stone Keeper",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Galgann Firehammer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Tablet of Will",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Shadowforge Cache",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Grimlok",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Archaedas",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "11",
      "label": "The Discs of Norgannon",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ancient Treasure",
      "indent": true,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Zul'Farrak": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_ZulFarrak.png",
    "entrance": false,
    "zoneName": "Zul'Farrak",
    "location": "Tanaris",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Antu'sul",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Theka the Martyr",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Witch Doctor Zum'rah",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Zul'Farrak Dead Hero",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Nekrum Gutchewer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Shadowpriest Sezz'ziz",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Dustwraith (Rare)",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Sergeant Bly",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Weegli Blastfuse",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Murta Grimgut",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Raven",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Oro Eyegouge",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Sandfury Executioner",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Hydromancer Velratha",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Gahz'rilla",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Elder Wildmane (Lunar Festival)",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Chief Ukorz Sandscalp",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ruuzlu",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Zerillis (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Sandarr Dunereaver (Rare)",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Maraudon": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_MaraudonEnt.png",
    "entrance": true,
    "zoneName": "Maraudon (Entrance)",
    "location": "Desolace",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "The Nameless Prophet (Lower)",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "B",
      "label": "Maraudon (Purple)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Maraudon (Orange)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "D",
      "label": "Maraudon (Portal, Lower)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Kolk <The First Kahn>",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Gelk <The Second Kahn>",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Magra <The Third Kahn>",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Cavindra",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_Maraudon.png",
    "entrance": false,
    "zoneName": "Maraudon",
    "location": "Desolace",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance (Orange)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Entrance (Purple)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Entrance (Portal)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Veng (The Fifth Khan)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Noxxion",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Razorlash",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Maraudos (The Fourth Khan)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Lord Vyletongue",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Meshlok the Harvester (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Celebras the Cursed",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Landslide",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Tinkerer Gizlock",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Rotgrip",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "11",
      "label": "Princess Theradras",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "12",
      "label": "Elder Splitrock (Lunar Festival)",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "The Temple of Atal'Hakkar": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_TheSunkenTempleEnt.png",
    "entrance": true,
    "zoneName": "Sunken Temple (Entrance)",
    "location": "Swamp of Sorrows",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Meeting Stone",
      "indent": true,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Jade (Rare)",
      "indent": true,
      "category": "green"
     },
     {
      "ref": "B",
      "label": "Sunken Temple",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Kazkaz the Unholy",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Zekkis (Rare)",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_TheSunkenTemple.png",
    "entrance": false,
    "zoneName": "Sunken Temple",
    "location": "Swamp of Sorrows",
    "pois": [
     {
      "ref": null,
      "label": "AKA: The Temple of Atal'Hakkar",
      "indent": false,
      "category": "orange"
     },
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Stairs",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Troll Minibosses",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Altar of Hakkar",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Atal'alarion",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Dreamscythe",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Weaver",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Avatar of Hakkar",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Jammal'an the Prophet",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ogom the Wretched",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Morphaz",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Hazzas",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Shade of Eranikus",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Essence Font",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Spawn of Hakkar (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Elder Starsong (Lunar Festival)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "1'-6') Statue Activation Order",
      "indent": false,
      "category": "green"
     }
    ]
   }
  ]
 },
 "Blackrock Depths": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_BlackrockMountainEnt.png",
    "entrance": true,
    "zoneName": "Blackrock Mountain (Entrance)",
    "location": "Searing Gorge / Burning Steppes",
    "pois": [
     {
      "ref": "A",
      "label": "Searing Gorge",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Burning Steppes",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Blackrock Depths (BRD)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Molten Core (MC)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "D",
      "label": "Blackrock Spire (Lower, LBRS)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Blackrock Spire (Upper, UBRS)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Blackwing Lair (BWL)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Bodley (Ghost)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Overmaster Pyron",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Lothos Riftwaker",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Franclorn Forgewright (Ghost)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Meeting Stone (BRD)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Orb of Command",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Meeting Stone (LBRS, UBRS)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Scarshield Quartermaster <Scarshield Legion>",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_BlackrockDepths.png",
    "entrance": false,
    "zoneName": "Blackrock Mountain: Blackrock Depths",
    "location": "Searing Gorge / Burning Steppes",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Lord Roccor",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Kharan Mighthammer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Commander Gor'shak",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Marshal Windsor",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "High Interrogator Gerstahn",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Ring of Law",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Anub'shiah",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Eviscerator",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Gorosh the Dervish",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Grizzle",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Hedrum the Creeper",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ok'thor the Breaker",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Theldren",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Lefty",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Malgen Longspear",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Gnashjaw",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Rotfang",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Va'jashni",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Houndmaster Grebmar",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Elder Morndeep (Lunar Festival)",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "High Justice Grimstone",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Monument of Franclorn Forgewright",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Pyromancer Loregrain",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "The Vault",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Warder Stilgiss",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Verek",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Watchman Doomgrip",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Fineous Darkvire",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "The Black Anvil",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Lord Incendius",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "11",
      "label": "Bael'Gar",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "12",
      "label": "The Shadowforge Lock",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "13",
      "label": "General Angerforge",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "14",
      "label": "Golem Lord Argelmach",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Schematic: Field Repair Bot 74A",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Blacksmithing Plans",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "15",
      "label": "The Grim Guzzler",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Hurley Blackbreath",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Lokhtos Darkbargainer",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Mistress Nagmara",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Phalanx",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Plugger Spazzring",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Private Rocknot",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ribbly Screwspigot",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "16",
      "label": "Ambassador Flamelash",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "17",
      "label": "Panzor the Invincible (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Blacksmithing Plans",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "18",
      "label": "Summoner's Tomb",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "19",
      "label": "The Lyceum",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "20",
      "label": "Magmus",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "21",
      "label": "Emperor Dagran Thaurissan",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Princess Moira Bronzebeard",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "22",
      "label": "The Black Forge",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "23",
      "label": "The Molten Core",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Core Fragment",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "24",
      "label": "Overmaster Pyron",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "25",
      "label": "Blacksmithing Plans",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Lower Blackrock Spire": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_BlackrockMountainEnt.png",
    "entrance": true,
    "zoneName": "Blackrock Mountain (Entrance)",
    "location": "Searing Gorge / Burning Steppes",
    "pois": [
     {
      "ref": "A",
      "label": "Searing Gorge",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Burning Steppes",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Blackrock Depths (BRD)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Molten Core (MC)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "D",
      "label": "Blackrock Spire (Lower, LBRS)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Blackrock Spire (Upper, UBRS)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Blackwing Lair (BWL)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Bodley (Ghost)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Overmaster Pyron",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Lothos Riftwaker",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Franclorn Forgewright (Ghost)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Meeting Stone (BRD)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Orb of Command",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Meeting Stone (LBRS, UBRS)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Scarshield Quartermaster <Scarshield Legion>",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_BlackrockSpireLower.png",
    "entrance": false,
    "zoneName": "Blackrock Mountain: Lower Blackrock Spire",
    "location": "Searing Gorge / Burning Steppes",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Blackrock Spire (Upper)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "C-F) Connection",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Vaelan",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Warosh",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Elder Stonefort (Lunar Festival)",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Roughshod Pike",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Spirestone Butcher (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Highlord Omokk",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Spirestone Battle Lord (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Spirestone Lord Magus (Rare)",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Shadow Hunter Vosh'gajin",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Fifth Mosh'aru Tablet",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Bijou",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "War Master Voone",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Sixth Mosh'aru Tablet",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Mor Grayhoof",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Bijou's Belongings",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "11",
      "label": "Human Remains",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Unfired Plate Gauntlets",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "12",
      "label": "Bannok Grimaxe (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "13",
      "label": "Mother Smolderweb",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "14",
      "label": "Crystal Fang (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "15",
      "label": "Urok's Tribute Pile",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Urok Doomhowl",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "16",
      "label": "Quartermaster Zigris",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "17",
      "label": "Halycon",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Gizrul the Slavener",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "18",
      "label": "Ghok Bashguud (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "19",
      "label": "Overlord Wyrmthalak",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "1",
      "label": "Burning Felguard (Rare)",
      "indent": false,
      "category": "green"
     }
    ]
   }
  ]
 },
 "Upper Blackrock Spire": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_BlackrockMountainEnt.png",
    "entrance": true,
    "zoneName": "Blackrock Mountain (Entrance)",
    "location": "Searing Gorge / Burning Steppes",
    "pois": [
     {
      "ref": "A",
      "label": "Searing Gorge",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Burning Steppes",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Blackrock Depths (BRD)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Molten Core (MC)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "D",
      "label": "Blackrock Spire (Lower, LBRS)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Blackrock Spire (Upper, UBRS)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Blackwing Lair (BWL)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": null,
      "label": "Bodley (Ghost)",
      "indent": true,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Overmaster Pyron",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Lothos Riftwaker",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Franclorn Forgewright (Ghost)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Meeting Stone (BRD)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Orb of Command",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Meeting Stone (LBRS, UBRS)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Scarshield Quartermaster <Scarshield Legion>",
      "indent": false,
      "category": "poi"
     }
    ]
   },
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_BlackrockSpireUpper.png",
    "entrance": false,
    "zoneName": "Blackrock Mountain: Upper Blackrock Spire",
    "location": "Searing Gorge / Burning Steppes",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Blackrock Spire (Lower)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "C-E) Connection",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Pyroguard Emberseer",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Solakar Flamewreath",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Father Flame",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Darkstone Tablet",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Doomrigger's Coffer",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Jed Runewatcher (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Goraluk Anvilcrack",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Warchief Rend Blackhand",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Gyth",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Awbee",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "The Beast",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Lord Valthalak",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Finkle Einhorn",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "General Drakkisath",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Drakkisath's Brand",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Blackwing Lair",
      "indent": false,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Dire Maul": {
  "levels": [
   {
    "label": "Entrance",
    "src": "assets/maps/atlas/CL_DireMaulEnt.png",
    "entrance": true,
    "zoneName": "Dire Maul (Entrance)",
    "location": "Feralas",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Dire Maul (East)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "C",
      "label": "Dire Maul (North)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "D",
      "label": "Dire Maul (West)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "1') Dire Pool",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "2') Dire Maul Arena",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Elder Mistwalker (Lunar Festival)",
      "indent": true,
      "category": "green"
     }
    ]
   },
   {
    "label": "North",
    "src": "assets/maps/atlas/CL_DireMaulNorth.png",
    "entrance": false,
    "zoneName": "Dire Maul (North)",
    "location": "Feralas",
    "pois": [
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Guard Mol'dar",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Stomper Kreeg",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Guard Fengus",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Knot Thimblejack",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Guard Slip'kik",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Captain Kromcrush",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "King Gordok",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Cho'Rush the Observer",
      "indent": true,
      "category": "poi"
     }
    ]
   },
   {
    "label": "West",
    "src": "assets/maps/atlas/CL_DireMaulWest.png",
    "entrance": false,
    "zoneName": "Dire Maul (West)",
    "location": "Feralas",
    "pois": [
     {
      "ref": null,
      "label": "Key: J'eevee's Jar (Lord Hel'nurath)",
      "indent": false,
      "category": "orange"
     },
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Pylons",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Shen'dralar Ancient",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Tendris Warpwood",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ancient Equine Spirit",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Illyanna Ravenoak",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ferra",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Magister Kalendris",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Tsu'zee (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Immol'thar",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Lord Hel'nurath",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Prince Tortheldrin",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "1') Library",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Falrin Treeshaper",
      "indent": true,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Lorekeeper Lydros",
      "indent": true,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Lorekeeper Javon",
      "indent": true,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Lorekeeper Kildrath",
      "indent": true,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Lorekeeper Mykos",
      "indent": true,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Shen'dralar Provisioner",
      "indent": true,
      "category": "green"
     },
     {
      "ref": null,
      "label": "Skeletal Remains of Kariel Winthalus",
      "indent": true,
      "category": "green"
     }
    ]
   },
   {
    "label": "East",
    "src": "assets/maps/atlas/CL_DireMaulEast.png",
    "entrance": false,
    "zoneName": "Dire Maul (East)",
    "location": "Feralas",
    "pois": [
     {
      "ref": null,
      "label": "A-C) Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "D",
      "label": "Exit",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Pusillin (Chase Begins)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Pusillin (Chase Ends)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Zevrim Thornhoof",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Hydrospawn",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Lethtendris",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Pimgib",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "Old Ironbark / Ironbark the Redeemed",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Alzzin the Wildshaper",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Isalien",
      "indent": true,
      "category": "poi"
     }
    ]
   }
  ]
 },
 "Scholomance": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_Scholomance.png",
    "entrance": false,
    "zoneName": "Scholomance",
    "location": "Western Plaguelands",
    "pois": [
     {
      "ref": null,
      "label": "Key: Blood of Innocents (Kirtonos the Herald)",
      "indent": false,
      "category": "orange"
     },
     {
      "ref": null,
      "label": "Key: Divination Scryer (Death Knight Darkreaver)",
      "indent": false,
      "category": "orange"
     },
     {
      "ref": "A",
      "label": "Entrance",
      "indent": false,
      "category": "location"
     },
     {
      "ref": null,
      "label": "B-C) Stairs",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Blood Steward of Kirtonos",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "The Deed to Southshore",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Kirtonos the Herald",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Jandice Barov",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "The Deed to Tarren Mill",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Rattlegore",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Death Knight Darkreaver",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Marduk Blackpool",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Vectus",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Ras Frostwhisper",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "The Deed to Brill",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Kormok",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Instructor Malicia",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Doctor Theolen Krastinov",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Lorekeeper Polkelt",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "11",
      "label": "The Ravenian",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "12",
      "label": "Lord Alexei Barov",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "The Deed to Caer Darrow",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "13",
      "label": "Lady Illucia Barov",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "14",
      "label": "Darkmaster Gandling",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "1') Torch Lever",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "2') Secret Chest",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "3') Alchemy Lab",
      "indent": false,
      "category": "green"
     }
    ]
   }
  ]
 },
 "Stratholme": {
  "levels": [
   {
    "label": "Map",
    "src": "assets/maps/atlas/CL_Stratholme.png",
    "entrance": false,
    "zoneName": "Stratholme",
    "location": "Eastern Plaguelands",
    "pois": [
     {
      "ref": null,
      "label": "Key: Various Postbox Keys (Postmaster Malown)",
      "indent": false,
      "category": "orange"
     },
     {
      "ref": "A",
      "label": "Entrance (Front)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "B",
      "label": "Entrance (Side)",
      "indent": false,
      "category": "location"
     },
     {
      "ref": "1",
      "label": "Skul (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Stratholme Courier",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Fras Siabi",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "2",
      "label": "Atiesh",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "3",
      "label": "Hearthsinger Forresten",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "4",
      "label": "The Unforgiven",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "5",
      "label": "Elder Farwhisper (Lunar Festival)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "6",
      "label": "Timmy the Cruel",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "7",
      "label": "Malor the Zealous",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Medallion of Faith",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "8",
      "label": "Crimson Hammersmith",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Blacksmithing Plans",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "9",
      "label": "Cannon Master Willey",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "10",
      "label": "Archivist Galford",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "11",
      "label": "Grand Crusader Dathrohan",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Balnazzar",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Sothos",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Jarien",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "12",
      "label": "Magistrate Barthilas",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "13",
      "label": "Aurius",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "14",
      "label": "Stonespine (Rare)",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "15",
      "label": "Baroness Anastari",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Black Guard Swordsmith",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Blacksmithing Plans",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": "16",
      "label": "Nerub'enkan",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "17",
      "label": "Maleki the Pallid",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "18",
      "label": "Ramstein the Gorger",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": "19",
      "label": "Baron Rivendare",
      "indent": false,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "Ysida Harmon",
      "indent": true,
      "category": "poi"
     },
     {
      "ref": null,
      "label": "1') Crusaders' Square Postbox",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "2') Market Row Postbox",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "3') Festival Lane Postbox",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "4') Elders' Square Postbox",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "5') King's Square Postbox",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "6') Fras Siabi's Postbox",
      "indent": false,
      "category": "green"
     },
     {
      "ref": null,
      "label": "3rd Box Opened: Postmaster Malown",
      "indent": false,
      "category": "green"
     }
    ]
   }
  ]
 }
};
